name: Run end-to-end-tests on pull-requests

on:
  pull_request:

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Read/save .m2 cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - uses: actions/setup-java@v1
        with:
          java-version: '11'


      - name: 'Build the code for soknadsmottaker'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@master
        with:
          component_name: soknadsmottaker

      - name: 'Build the code for soknadsfillager (this PR)'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@master
        with:
          component_name: soknadsfillager
          branch: ${GITHUB_HEAD_REF} # Branch of current PR

      - name: 'Build the code for soknadsarkiverer'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@master
        with:
          component_name: soknadsarkiverer

      - name: 'Build the code for arkiv-mock'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@master
        with:
          component_name: archiving-infrastructure
          sub_directory: arkiv-mock

      - name: 'Run the end-to-end-tests'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@master
        with:
          component_name: archiving-infrastructure
          sub_directory: end-to-end-tests
          skip_tests: false
          run_docker_build: false
